"""add occurrence_count to finding_instances

Revision ID: fc6a289fcc4b
Revises: 31cd029594af
Create Date: 2026-08-21 07:42:14.553388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6a289fcc4b'
down_revision: Union[str, None] = '31cd029594af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this is safe to run against a database that
    # already has finding_instances rows (e.g. a real Pentera import
    # already loaded locally) -- existing rows get occurrence_count=1,
    # matching "1 for a normal, non-duplicated observation".
    op.add_column(
        'finding_instances',
        sa.Column('occurrence_count', sa.Integer(), nullable=False, server_default='1'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding_instances', 'occurrence_count')
    # ### end Alembic commands ###
